### ISSUE TITLE
Should check if constant 'DS' is defined

### ISSUE THREAD

**Issue by tuankiet1708** [Vinelab/lucid-console#26]
At **line 23** of file **src/Finder.php**, I suggest that you should check if constant 'DS' is defined to avoid crashes, as following:

```
if (!defined('DS')) {
    define('DS', DIRECTORY_SEPARATOR);
}
```

**Comment by rfpdl** [comment]
Getting this error when I added a new package.

Can we follow up on this?

**Comment by Mulkave** [comment]
Wow, pretty old. Sorry for the delay here, this repo wasn't being followed-up regularly on issues. 😞 

Anyway, it's been resolved in the new repo here: https://github.com/lucidarch/lucid/blob/main/src/Finder.php#L14
