### ISSUE TITLE
lucid component

### ISSUE THREAD

**Issue by rebornishard** [Vinelab/lucid-console#31]
seems interesting, how do you do this : 
``
@include('lucid::components.toast')
    @include('lucid::components.code-preview')
    @include('lucid::components.create-job')
    @include('lucid::components.create-feature')
    @include('lucid::components.create-service')
    @include('lucid::components.add-menu')
``

**Comment by Mulkave** [comment]
@rebornishard this is done through view namespace registration. It can be done in a service provider with the following:

```php
View::addNamespace('lucid', base_path('resources/views/components'));
```
