### ISSUE TITLE
Support laravel 6

### ISSUE THREAD

**Issue by vanthao03596** [Vinelab/lucid-console#42]
Please add support laravel 6.

**Comment by logan-jobzmall** [comment]
I have a branch and tagged version here: https://packagist.org/packages/jobzmall/lucid-laravel-console#v6.0.2

Let me know if you run into any issues. I am not putting in a PR, because this was a quick hack that removed incompatible dependencies (and some code because of that). @vanthao03596

**Comment by harris21** [comment]
Hello people,

You can already find support for Laravel 6 by either using the master branch or the 6.0 branch.
