### ISSUE TITLE
Unable to prepare route [lucid/dashboard] for serialization. Uses Closure.

### ISSUE THREAD

**Issue by vytsci** [Vinelab/lucid-console#46]
Routes cache is not working with lucid dashboard.

**Comment by Mulkave** [comment]
@kohlerdominik transferred the issue here.

@vytsci which version of Lucid/Laravel are you using?

**Comment by vytsci** [comment]
Currently it is 5.8.37. It was 5.6 before, but I have not checked this dashboard since this issue was reported.

**Comment by Mulkave** [comment]
Understood. Can you please confirm that the issue persists?

**Comment by vytsci** [comment]
> Understood. Can you please confirm that the issue persists?

Ok Ill check soon.
