### ISSUE TITLE
FinderFacade return also directories not only file.

### ISSUE THREAD

**Issue by glorand** [Vinelab/lucid-console#7]
'/analysis'
Here the FinderFacade return also directories not only files. 
Would be nice to check the file list before we pass to view is is a file and if is readable.

**Comment by Mulkave** [comment]
Can you please elaborate on where the issue in returning the directories for analysis is?

**Comment by glorand** [comment]
Yes, 
so we start from a fresh install of lucid. Basically the issue is for all the entities. It's relative easy to reproduce, just create an empty folder under the directories Service, Feature, Job.
The bug was found under Windows, Php v. 5.6.x. 
But you can test in a very easy way the; just run manually FinderFacade "findFiles" function on a structure created by you, and will see that returns also folders not only files.

**Comment by Mulkave** [comment]
@glorand Thanks for the note. Looking at the code in the `Analyser` class, the `SebastianBergmann\FinderFacade\FinderFacade` instance's call to `findFiles` is what the `PHPLOCAnalyser` requires so I would refrain from changing that for it's exactly what is being done in the original package as well https://github.com/sebastianbergmann/phploc/blob/master/src/CLI/Command.php#L244
